# This file was moved from the project root to the example/ folder.
# All build contexts and dockerfile paths have been updated accordingly.

services:
  mcp_metric_server:
    build:
      context: ../src/
      dockerfile: Dockerfile
    container_name: mcp_metric_server
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    networks:
      - mcpnet

  mcp_workflow_server:
    build:
      context: mcp_evaluation_workflow_server
      dockerfile: Dockerfile
    container_name: mcp_workflow_server
    ports:
      - "8001:8000"
    restart: unless-stopped
    depends_on:
      - mcp_metric_server
    networks:
      - mcpnet

  mcp_context_server:
    build:
      context: other_mcp_servers/rag
      dockerfile: Dockerfile
    container_name: mcp_context_server
    ports:
      - "8002:8000"
    restart: unless-stopped
    networks:
      - mcpnet

  mcp_reference_data_server:
    build:
      context: other_mcp_servers/reference_data
      dockerfile: Dockerfile
    container_name: mcp_reference_data_server
    ports:
      - "8003:8000"
    restart: unless-stopped
    networks:
      - mcpnet

networks:
  mcpnet:
    driver: bridge
